# Generated by Django 5.2.5 on 2025-10-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
