# Generated by Django 5.2.5 on 2025-11-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='opening_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
